# Generated by Django 3.2 on 2021-04-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_elv', models.CharField(blank=True, db_column='NOM_ELV', max_length=255, null=True)),
                ('pwd_elv', models.CharField(blank=True, db_column='PWD_ELV', max_length=255, null=True)),
                ('date_nai_elv', models.DateField(blank=True, db_column='DATE_NAI_ELV', null=True)),
            ],
            options={
                'db_table': 'ELEVE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ens', models.CharField(blank=True, db_column='NOM_ENS', max_length=255, null=True)),
                ('pwd_ens', models.CharField(blank=True, db_column='PWD_ENS', max_length=255, null=True)),
                ('date_nai_ens', models.DateField(blank=True, db_column='DATE_NAI_ENS', null=True)),
            ],
            options={
                'db_table': 'ENSEIGNANT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desig_ex', models.CharField(blank=True, db_column='DESIG', max_length=255, null=True)),
                ('descr_ex', models.TextField(blank=True, db_column='DESCR', null=True)),
                ('lien', models.CharField(blank=True, db_column='LIEN', max_length=255, null=True)),
            ],
            options={
                'db_table': 'EXERCICE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desig_ins', models.CharField(blank=True, db_column='DESIG', max_length=255, null=True)),
                ('descr_ins', models.TextField(blank=True, db_column='DESCR', null=True)),
                ('lien', models.CharField(blank=True, db_column='LIEN', max_length=255, null=True)),
                ('outputgeneration', models.TextField(blank=True, db_column='outputGeneration', null=True)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.exercice')),
            ],
            options={
                'db_table': 'INSTANCE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desig_nv', models.CharField(blank=True, db_column='DESIG_NV', max_length=32, null=True)),
                ('desc_nv', models.CharField(blank=True, db_column='DESC_NV', max_length=255, null=True)),
            ],
            options={
                'db_table': 'NIVEAU',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Repertoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desig_rep', models.CharField(blank=True, db_column='DESIG_REP', max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, db_column='TYPE', null=True)),
                ('lien', models.CharField(blank=True, db_column='LIEN', max_length=255, null=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.enseignant')),
            ],
            options={
                'db_table': 'REPERTOIRE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Virtualmachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desig_vm', models.CharField(blank=True, db_column='DESIG_VM', max_length=255, null=True)),
                ('desc_vm', models.CharField(blank=True, db_column='DESC_VM', max_length=255, null=True)),
                ('lien', models.CharField(blank=True, db_column='LIEN', max_length=255, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.instance')),
                ('repertoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.repertoire')),
            ],
            options={
                'db_table': 'VIRTUALMACHINE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(db_column='VALUE')),
                ('at_time', models.DateTimeField(blank=True, db_column='AT_TIME', null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.eleve')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.exercice')),
            ],
            options={
                'db_table': 'SCORE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, db_column='SUBJECT', max_length=255, null=True)),
                ('content', models.TextField(blank=True, db_column='CONTENT', null=True)),
                ('type', models.IntegerField(blank=True, db_column='TYPE', null=True)),
                ('at_time', models.DateTimeField(blank=True, db_column='AT_TIME', null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.eleve')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.enseignant')),
            ],
            options={
                'db_table': 'MESSAGE',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='instance',
            name='repertoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.repertoire'),
        ),
        migrations.CreateModel(
            name='Imagedocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desig_doc', models.CharField(blank=True, db_column='DESIG_Doc', max_length=255, null=True)),
                ('desc_doc', models.CharField(blank=True, db_column='DESC_Doc', max_length=255, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.instance')),
                ('repertoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.repertoire')),
            ],
            options={
                'db_table': 'IMAGEDOCKER',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desig_grp', models.CharField(blank=True, db_column='DESIG_GRP', max_length=32, null=True)),
                ('desc_grp', models.CharField(blank=True, db_column='DESC_GRP', max_length=255, null=True)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.niveau')),
            ],
            options={
                'db_table': 'GROUPE',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='exercice',
            name='repertoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.repertoire'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.groupe'),
        ),
    ]
