# Generated by Django 3.2 on 2021-04-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Msg',
        ),
    ]
