# Generated by Django 3.2 on 2021-04-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='json_file',
            field=models.TextField(blank=True, db_column='JSON_FILE', null=True),
        ),
    ]
