# Generated by Django 3.2 on 2021-04-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_exercice_json_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='but',
            field=models.TextField(blank=True, db_column='BUT', null=True),
        ),
    ]
