# Generated by Django 3.2 on 2021-04-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_exercice_but'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='but',
            field=models.CharField(blank=True, db_column='BUT', max_length=255, null=True),
        ),
    ]
