# Generated by Django 3.2 on 2021-04-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_exercice_but'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
