# Generated by Django 3.2 on 2021-04-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='descr_ins',
        ),
    ]
